### ISSUE TITLE
missing/undocumented dependency: setuptools

### ISSUE THREAD

**Issue by hex-m** [JOJ0/synadm#33]
Following the [installation process](https://github.com/JOJ0/synadm/blob/master/README.md#3-install-package-globally) on my server (Debian 10) I get the following error:

```
# python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 18, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'
```

The solution for me was `apt install python3-setuptools`.

**Comment by JOJ0** [comment]
hi, thanks for the report. you installed into a venv or systemwide using sudo?

**Comment by hex-m** [comment]
Systemwide, but logged in as root - so without sudo - if that matters.

**Comment by JOJ0** [comment]
I think when a venv is used, setuptools is put into the venv as a first thing, so probably no need there, but since you were following the sudo part of the readme I think it will be best I just add a hint to make sure python3-setuptools is installed on Debian systems. Need to have a look what RedHatish systems package is called. Since I use a lot of Python tools and even code Python I probably never realised that installing setuptools on the maching "is a thing" It's just always there, somebody did it for me already haha :-) Thanks for the report again!

**Comment by hex-m** [comment]
I just checked on a CentOS 8 system. The package is called `python3-setuptools` there.

Thanks for the helpful tool and the friendly communication.

cheers,
hex

**Comment by JOJ0** [comment]
don't worry! I just realized I could just hit the edit button myself and spare you the way around a PR for just a line of text :-) It's in there, please review and close this issue if you like it. Thanks again for the report! Helps me and other users! Great!

**Comment by hex-m** [comment]
Fixed by https://github.com/JOJ0/synadm/commit/771e533402b06b02194d3e77874556e5ae4dd5c1

Thanks!
