### ISSUE TITLE
How to delete local media for specific user ?

### ISSUE THREAD

**Issue by githuberyt** [JOJ0/synadm#35]
How to delete local media for a specific user ?

**Comment by JOJ0** [comment]
@githuberyt good news. have a look on #32 
I implemented ‘synadm user media’ command
please give it a try. it’s in master branch. just update you r installation as described in readme.
hope that helps!

**Comment by JOJ0** [comment]
Hi @githuberyt, did you find the time to try this out? I'd like to close this issue.
The commands you need to e.g delete all media of a user uploaded before this year, do:
```
synadm media @user:example.org -s created_ts  # find out media uploaded by user and sort by upload date
synadm media delete -i <media id>  # delete one of the media id's found before
```

you could certainly also loop the deletion of the found ids. With bash something like this:
```
for media in <media id 1><media id 2> <media id 3>; do synadm media delete -i $media; done
```

Is this sufficient for your needs or are you aiming for a completely automated approach? Should also be possible with some filtering using the tool "jq". If you need that I could maybe also help but am not a "jq" expert. Could take som time.

Just get back to me if you need anything else.
I am closing this issue since all the features needed to solve it are available in https://github.com/JOJ0/synadm/releases/tag/v0.28
